### ISSUE TITLE
Files and folders are not being created according to "structure.json"

### ISSUE THREAD

**Issue by 0018akhil** [HushmKun/Artec#4]
![1](https://github.com/HushmKun/Artec/assets/62931444/ebe9f113-3f00-463a-9a14-2a11b4509b70)
This is my structure.json file

![2](https://github.com/HushmKun/Artec/assets/62931444/9885391f-cd49-444a-9e1d-36ba3388e749)
Executed artech command.
But still creates standard folders.

![3](https://github.com/HushmKun/Artec/assets/62931444/8387d8c6-8cb1-4f85-a261-24fbf825323b)

**Comment by 0018akhil** [comment]
![1](https://github.com/HushmKun/Artec/assets/62931444/3457998d-9cbb-402b-8207-ab0a7d3d1862)

But still creating the standard folders not following structure.json

**Comment by HushmKun** [comment]
Okay, This just became personal 😅😂.
Gonna work on this. 

Thanks for notifying me.

**Comment by HushmKun** [comment]
Can you try it with the v0.1.2 and ```-v``` flag & tell me ? 

Also Did you install it from pip or cloned it ?

**Comment by 0018akhil** [comment]
Yes, I have installed it from pip. pip holds version 0.1.1

I have tried installing it by cloning it with version 0.1.2 this is the result.

![image](https://github.com/HushmKun/Artec/assets/62931444/59197f4c-8660-421d-a478-7a4df6ce61cc)

**Comment by HushmKun** [comment]
Okay, do you mind contacting me through Discord ```hushm``` ?

**Comment by 0018akhil** [comment]
Hey, @HushmKun 

![image](https://github.com/HushmKun/Artec/assets/62931444/173a9e77-27b5-4b78-8c81-f44b4d03153b)

The 'U' mode has been removed from **codecs**.

So I tried have updated it from '**rU**' mode to '**r**' it is working fine now.
![image](https://github.com/HushmKun/Artec/assets/62931444/a470f34a-f314-410e-a97a-9cfae780392a)

**Comment by HushmKun** [comment]
Fixed it, Thanks @0018akhil.

With that, This issue is marked as done.
